# Profiles
ZCL_HA_PROFILE = 0x0104

# Clusters
ZCL_CLUSTER_BASIC = 0x0000
ZCL_CLUSTER_ON_OFF = 0x0006
ZCL_CLUSTER_ON_OFF_SWITCH_CONFIG = 0x0007
ZCL_CLUSTER_MULTISTATE_INPUT_BASIC = 0x0012
ZCL_CLUSTER_LEVEL_CONTROL = 0x0008
ZCL_CLUSTER_GROUPS = 0x0004
ZCL_CLUSTER_WINDOW_COVERING = 0x0102
ZCL_CLUSTER_COVER_SWITCH_CONFIG = 0xFC01

# Attributes - Global
ZCL_ATTR_GLOBAL_CLUSTER_REVISION = 0xFFFD

# Attributes - Basic cluster
ZCL_ATTR_BASIC_ZCL_VER = 0x0000
ZCL_ATTR_BASIC_APP_VER = 0x0001
ZCL_ATTR_BASIC_STACK_VER = 0x0002
ZCL_ATTR_BASIC_HW_VER = 0x0003
ZCL_ATTR_BASIC_MFR_NAME = 0x0004
ZCL_ATTR_BASIC_MODEL_ID = 0x0005
ZCL_ATTR_BASIC_DATE_CODE = 0x0006
ZCL_ATTR_BASIC_POWER_SOURCE = 0x0007
ZCL_ATTR_BASIC_LOC_DESC = 0x0010
ZCL_ATTR_BASIC_PHY_ENV = 0x0011
ZCL_ATTR_BASIC_DEV_ENABLED = 0x0012
ZCL_ATTR_BASIC_ALARM_MASK = 0x0013
ZCL_ATTR_BASIC_DISABLE_LOCAL_CFG = 0x0014
ZCL_ATTR_BASIC_SW_BUILD_ID = 0x4000

ZCL_ATTR_BASIC_DEVICE_CONFIG = 0xFF00
ZCL_ATTR_BASIC_STATUS_LED_STATE = 0xFF01
ZCL_ATTR_BASIC_MULTI_PRESS_RESET_COUNT = 0xFF02

# Attributes - On/Off cluster
ZCL_ATTR_ONOFF = 0x0000
ZCL_ATTR_START_UP_ONOFF = 0x4003

ZCL_ATTR_ONOFF_INDICATOR_MODE = 0xFF01
ZCL_ATTR_ONOFF_INDICATOR_STATE = 0xFF02

# Attributes - On/Off configuration cluster
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_TYPE = 0x0000
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_ACTIONS = 0x0010
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_MODE = 0xFF00
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_RELAY_MODE = 0xFF01
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_RELAY_INDEX = 0xFF02
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_LONG_PRESS_DUR = 0xFF03
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_LEVEL_MOVE_RATE = 0xFF04
ZCL_ATTR_ONOFF_CONFIGURATION_SWITCH_BINDING_MODE = 0xFF05

# Attributes - Multistate cluster
ZCL_ATTR_MULTISTATE_INPUT_NUMBER_OF_STATES = 0x004A
ZCL_ATTR_MULTISTATE_INPUT_OUT_OF_SERVICE = 0x0051
ZCL_ATTR_MULTISTATE_INPUT_PRESENT_VALUE = 0x0055
ZCL_ATTR_MULTISTATE_INPUT_STATUS_FLAGS = 0x006F

# Attributes - Groups cluster
ZCL_ATTR_GROUP_NAME_SUPPORT = 0x0000

# Attributes - Window Covering cluster
ZCL_ATTR_WINDOW_COVERING_MOVING = 0xFF00
ZCL_ATTR_WINDOW_COVERING_MOTOR_REVERSAL = 0xFF01

# Attributes - Cover Switch Configuration cluster
ZCL_ATTR_COVER_SWITCH_SWITCH_TYPE = 0x0000
ZCL_ATTR_COVER_SWITCH_COVER_INDEX = 0x0001
ZCL_ATTR_COVER_SWITCH_REVERSAL = 0x0002
ZCL_ATTR_COVER_SWITCH_LOCAL_MODE = 0x0003
ZCL_ATTR_COVER_SWITCH_BINDED_MODE = 0x0004
ZCL_ATTR_COVER_SWITCH_LONG_PRESS_DURATION = 0x0005

# Enum values - On/Off cluster
ZCL_START_UP_ONOFF_SET_ONOFF_TO_OFF = 0x00
ZCL_START_UP_ONOFF_SET_ONOFF_TO_ON = 0x01
ZCL_START_UP_ONOFF_SET_ONOFF_TOGGLE = 0x02
ZCL_START_UP_ONOFF_SET_ONOFF_TO_PREVIOUS = 0xFF

ZCL_ONOFF_INDICATOR_MODE_SAME = 0x00
ZCL_ONOFF_INDICATOR_MODE_OPPOSITE = 0x01
ZCL_ONOFF_INDICATOR_MODE_MANUAL = 0x02

# Enum values - On/Off configuration cluster
ZCL_ONOFF_CONFIGURATION_SWITCH_TYPE_TOGGLE = 0x00
ZCL_ONOFF_CONFIGURATION_SWITCH_TYPE_MOMENTARY = 0x01
ZCL_ONOFF_CONFIGURATION_SWITCH_TYPE_MOMENTARY_NC = 0x02

ZCL_ONOFF_CONFIGURATION_SWITCH_ACTION_ONOFF = 0x00
ZCL_ONOFF_CONFIGURATION_SWITCH_ACTION_OFFON = 0x01
ZCL_ONOFF_CONFIGURATION_SWITCH_ACTION_TOGGLE_SIMPLE = 0x02
ZCL_ONOFF_CONFIGURATION_SWITCH_ACTION_TOGGLE_SMART_SYNC = 0x03
ZCL_ONOFF_CONFIGURATION_SWITCH_ACTION_TOGGLE_SMART_OPPOSITE = 0x04

ZCL_ONOFF_CONFIGURATION_RELAY_MODE_DETACHED = 0x00
ZCL_ONOFF_CONFIGURATION_RELAY_MODE_RISE = 0x01
ZCL_ONOFF_CONFIGURATION_RELAY_MODE_LONG = 0x02
ZCL_ONOFF_CONFIGURATION_RELAY_MODE_SHORT = 0x03

ZCL_ONOFF_CONFIGURATION_BINDED_MODE_RISE = 0x01
ZCL_ONOFF_CONFIGURATION_BINDED_MODE_LONG = 0x02
ZCL_ONOFF_CONFIGURATION_BINDED_MODE_SHORT = 0x03

# Enum values - Level cluster
ZCL_LEVEL_MOVE_UP = 0x00
ZCL_LEVEL_MOVE_DOWN = 0x01

# Enum values - Window Covering cluster
ZCL_WINDOW_COVERING_MOVING_STOPPED = 0
ZCL_WINDOW_COVERING_MOVING_OPENING = 1
ZCL_WINDOW_COVERING_MOVING_CLOSING = 2

# Enum values - Cover Switch Configuration cluster
ZCL_COVER_SWITCH_TYPE_TOGGLE = 0x00
ZCL_COVER_SWITCH_TYPE_MOMENTARY = 0x01

ZCL_COVER_SWITCH_MODE_IMMEDIATE = 0x00
ZCL_COVER_SWITCH_MODE_SHORT_PRESS = 0x01
ZCL_COVER_SWITCH_MODE_LONG_PRESS = 0x02
ZCL_COVER_SWITCH_MODE_HYBRID = 0x03

# Commands - On/Off Cluster
ZCL_CMD_ONOFF_OFF = 0x00
ZCL_CMD_ONOFF_ON = 0x01
ZCL_CMD_ONOFF_TOGGLE = 0x02
ZCL_CMD_OFF_WITH_EFFECT = 0x40
ZCL_CMD_ON_WITH_RECALL_GLOBAL_SCENE = 0x41
ZCL_CMD_ON_WITH_TIMED_OFF = 0x42

# Commands - Level Cluster
ZCL_CMD_LEVEL_MOVE_TO_LEVEL = 0x00
ZCL_CMD_LEVEL_MOVE = 0x01
ZCL_CMD_LEVEL_STEP = 0x02
ZCL_CMD_LEVEL_STOP = 0x03
ZCL_CMD_LEVEL_MOVE_TO_LEVEL_WITH_ON_OFF = 0x04
ZCL_CMD_LEVEL_MOVE_WITH_ON_OFF = 0x05
ZCL_CMD_LEVEL_STEP_WITH_ON_OFF = 0x06
ZCL_CMD_LEVEL_STOP_WITH_ON_OFF = 0x07

ZCL_LEVEL_MOVE_UP = 0x00
ZCL_LEVEL_MOVE_DOWN = 0x01

# Commands - Window Covering Cluster
ZCL_CMD_WINDOW_COVERING_UP_OPEN = 0x00
ZCL_CMD_WINDOW_COVERING_DOWN_CLOSE = 0x01
ZCL_CMD_WINDOW_COVERING_STOP = 0x02

# Data types (not currently used in tests, provided for completeness)
ZCL_DATA_TYPE_NO_DATA = 0x00
ZCL_DATA_TYPE_DATA8 = 0x08
ZCL_DATA_TYPE_DATA16 = 0x09
ZCL_DATA_TYPE_DATA24 = 0x0A
ZCL_DATA_TYPE_DATA32 = 0x0B
ZCL_DATA_TYPE_DATA40 = 0x0C
ZCL_DATA_TYPE_DATA48 = 0x0D
ZCL_DATA_TYPE_DATA56 = 0x0E
ZCL_DATA_TYPE_DATA64 = 0x0F
ZCL_DATA_TYPE_BOOLEAN = 0x10
ZCL_DATA_TYPE_BITMAP8 = 0x18
ZCL_DATA_TYPE_BITMAP16 = 0x19
ZCL_DATA_TYPE_BITMAP24 = 0x1A
ZCL_DATA_TYPE_BITMAP32 = 0x1B
ZCL_DATA_TYPE_BITMAP40 = 0x1C
ZCL_DATA_TYPE_BITMAP48 = 0x1D
ZCL_DATA_TYPE_BITMAP56 = 0x1E
ZCL_DATA_TYPE_BITMAP64 = 0x1F
ZCL_DATA_TYPE_UINT8 = 0x20
ZCL_DATA_TYPE_UINT16 = 0x21
ZCL_DATA_TYPE_UINT24 = 0x22
ZCL_DATA_TYPE_UINT32 = 0x23
ZCL_DATA_TYPE_UINT40 = 0x24
ZCL_DATA_TYPE_UINT48 = 0x25
ZCL_DATA_TYPE_UINT56 = 0x26
ZCL_DATA_TYPE_UINT64 = 0x27
ZCL_DATA_TYPE_INT8 = 0x28
ZCL_DATA_TYPE_INT16 = 0x29
ZCL_DATA_TYPE_INT24 = 0x2A
ZCL_DATA_TYPE_INT32 = 0x2B
ZCL_DATA_TYPE_INT40 = 0x2C
ZCL_DATA_TYPE_INT48 = 0x2D
ZCL_DATA_TYPE_INT56 = 0x2E
ZCL_DATA_TYPE_INT64 = 0x2F
ZCL_DATA_TYPE_ENUM8 = 0x30
ZCL_DATA_TYPE_ENUM16 = 0x31
ZCL_DATA_TYPE_SEMI_PREC = 0x38
ZCL_DATA_TYPE_SINGLE_PREC = 0x39
ZCL_DATA_TYPE_DOUBLE_PREC = 0x3A
ZCL_DATA_TYPE_OCTET_STR = 0x41
ZCL_DATA_TYPE_CHAR_STR = 0x42
ZCL_DATA_TYPE_LONG_OCTET_STR = 0x43
ZCL_DATA_TYPE_LONG_CHAR_STR = 0x44
ZCL_DATA_TYPE_ARRAY = 0x48
ZCL_DATA_TYPE_STRUCT = 0x4C
ZCL_DATA_TYPE_SET = 0x50
ZCL_DATA_TYPE_BAG = 0x51
ZCL_DATA_TYPE_TOD = 0xE0
ZCL_DATA_TYPE_DATE = 0xE1
ZCL_DATA_TYPE_UTC = 0xE2
ZCL_DATA_TYPE_CLUSTER_ID = 0xE8
ZCL_DATA_TYPE_ATTR_ID = 0xE9
ZCL_DATA_TYPE_BAC_OID = 0xEA
ZCL_DATA_TYPE_IEEE_ADDR = 0xF0
ZCL_DATA_TYPE_128_BIT_SEC_KEY = 0xF1
ZCL_DATA_TYPE_UNKNOWN = 0xFF
