#!/usr/bin/env bash
set -euo pipefail

# ----------------------------------------------------------------------------
# oras_push_all.sh
#
# Batch-push firmware blobs to OCI registry (ghcr.io) with metadata annotations.

# Overview:
#   - Reads a manifest file (local_path|remote_ref)
#   - Pushes each firmware file to its OCI reference using the ORAS CLI
#   - Attaches metadata for GHCR display using an annotations JSON file
#     produced by `helper_scripts/prepare_release.py` (see that script for
#     annotation key details).
#
# What are "correct annotations"?
#   - OCI annotations are metadata attached to each artifact and the manifest.
#   - These ensure blobs are shown as firmware with meaningful info in GHCR UI.
#   - See prepare_release.py for annotation key details.
#   - Per-file title annotation helps distinguish blobs in registry listings.
#
# This script:
#   - Reads a manifest file (lines: local_path|remote_ref)
#   - Generates an ORAS annotation JSON file (with $manifest and per-file entries)
#   - Pushes each firmware file to its OCI reference using ORAS CLI
#   - Attaches metadata for ghcr.io display (title, description, version, etc.)
#
# Arguments (all required):
#   -m MANIFEST: path to oci_push_manifest.txt (list of files and refs)
#   -r REPO: owner/repo (e.g. youtux/tuya-zigbee-switch)
#   -t TAG: release tag (e.g. v1.2.3)
#   -a ANNOTATIONS: path to annotations JSON file (generated by prepare_release.py)
#   -a ANNOTATIONS: path to annotations JSON file (required)
#
# Example:
#   ./oras_push_all.sh -m oci_push_manifest.txt -r youtux/tuya-zigbee-switch -t v1.2.3
#
# Requires:
#   - ORAS CLI installed and authenticated (oras)
#   - An annotations JSON file produced by `helper_scripts/prepare_release.py`
# ----------------------------------------------------------------------------

manifest=""
repo=""
tag=""
annotation_file=""

while getopts "m:r:t:a:" opt; do
  case $opt in
    m) manifest="$OPTARG" ;;
    r) repo="$OPTARG" ;;
    t) tag="$OPTARG" ;;
    a) annotation_file="$OPTARG" ;;
    *)
      echo "Usage: $0 -m MANIFEST -r REPO -t TAG [-a ANNOTATIONS]" >&2
      exit 1
      ;;
  esac
done

if [ -z "$manifest" ] || [ -z "$repo" ] || [ -z "$tag" ] || [ -z "$annotation_file" ]; then
  echo "Usage: $0 -m MANIFEST -r REPO -t TAG -a ANNOTATIONS" >&2
  echo "All arguments are required; ANNOTATIONS must be provided to avoid ambiguity." >&2
  exit 1
fi

if [ ! -f "$manifest" ]; then
  echo "Manifest file not found: $manifest" >&2
  exit 2
fi

# Annotation file must be provided via -a and must exist
if [ ! -f "$annotation_file" ]; then
  echo "Annotations file not found: $annotation_file. Run prepare_release.py to generate it before pushing." >&2
  exit 3
fi

echo "Using annotation file: $annotation_file"

# Process each line in the manifest file:
# - Split line into local (firmware file path) and remote (OCI reference)
# - Skip lines where either part is empty (e.g., blank lines)
# - Push valid firmware files to their OCI destination
while IFS='|' read -r local remote; do
  if [ -z "$local" ] || [ -z "$remote" ]; then
    # Skip invalid or blank lines
    continue
  fi
  echo "Pushing $local -> $remote"
  oras push --annotation-file "$annotation_file" --artifact-type "application/octet-stream" "$remote" "$local"
done < "$manifest"

echo "All pushes completed"
